# Generated by Django 4.2.7 on 2023-12-13 06:13

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0010_customuser_last_device_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='security_question_1',
            field=models.CharField(blank=True, choices=[('favorite_color', 'What is your favorite color?'), ('first_pet', 'What was the name of your first pet?'), ('birth_city', 'In which city were you born?'), ('favorite_book', 'What is your favorite book?'), ('high_school', 'Which high school did you attend?')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='security_question_2',
            field=models.CharField(blank=True, choices=[('favorite_color', 'What is your favorite color?'), ('first_pet', 'What was the name of your first pet?'), ('birth_city', 'In which city were you born?'), ('favorite_book', 'What is your favorite book?'), ('high_school', 'Which high school did you attend?')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
